{% set name = "joker" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/candid82/joker/archive/v{{ version }}.tar.gz
  sha256: 5e2f5bc5d03ae456cf032d73f7fed0b4475e23b5a05b65abb97256362ebeb7c8

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - joker --help

about:
  home: https://github.com/candid82/joker
  license: EPL-1.0
  license_file:
    - LICENSE
  summary: Small Clojure interpreter, linter and formatter.
  dev_url: https://github.com/candid82/joker

extra:
  recipe-maintainers:
    - danielnachun
