schema_version: 1

context:
  version: "1.6.0"

package:
  name: joker
  version: ${{ version }}

source:
  url: https://github.com/candid82/joker/archive/v${{ version }}.tar.gz
  sha256: f7d48c503feed4ee8e2680febad07ba0cdbb7dae5886e119261163c27cf28899

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - joker --help

about:
  license: EPL-1.0
  license_file:
    - LICENSE
  summary: Small Clojure interpreter, linter and formatter.
  homepage: https://github.com/candid82/joker
  repository: https://github.com/candid82/joker

extra:
  recipe-maintainers:
    - danielnachun
