schema_version: 1

context:
  version: "1.7.2"

package:
  name: joker
  version: ${{ version }}

source:
  url: https://github.com/candid82/joker/archive/v${{ version }}.tar.gz
  sha256: 5946755e194e44dbf4b79e35d47b4f17be03804fe6a9633f1c0a279f22183c16

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - joker --help

about:
  license: EPL-1.0
  license_file:
    - LICENSE
  summary: Small Clojure interpreter, linter and formatter.
  homepage: https://github.com/candid82/joker
  repository: https://github.com/candid82/joker

extra:
  recipe-maintainers:
    - danielnachun
