schema_version: 1

context:
  version: "1.8.1"

package:
  name: joker
  version: ${{ version }}

source:
  url: https://github.com/candid82/joker/archive/v${{ version }}.tar.gz
  sha256: 40f2f4989107c3ee070f18b55ce7c51ef6adceba44d8519b77bff478861ebda3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - joker --help

about:
  license: EPL-1.0
  license_file:
    - LICENSE
  summary: Small Clojure interpreter, linter and formatter.
  homepage: https://github.com/candid82/joker
  repository: https://github.com/candid82/joker

extra:
  recipe-maintainers:
    - danielnachun
