schema_version: 1

context:
  version: "1.9.0"

package:
  name: joker
  version: ${{ version }}

source:
  url: https://github.com/candid82/joker/archive/v${{ version }}.tar.gz
  sha256: 515c2219336b9b480413a4a8e306c3f2d1d0dc9c84183b0c0446a5f717e783ef

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - joker --help

about:
  license: EPL-1.0
  license_file:
    - LICENSE
  summary: Small Clojure interpreter, linter and formatter.
  homepage: https://github.com/candid82/joker
  repository: https://github.com/candid82/joker

extra:
  recipe-maintainers:
    - danielnachun
